version: "3.4"
services:
  tycspider:
    image: svr.tycspider:v1.4-miniconda
    container_name: tycspider
#    ports:
#      - ""
    expose:
      - "80"
    working_dir: /usr/src/app/
    networks:
      cct-backstage:
        aliases:
          - tycspider
        ipv4_address: 172.30.0.20
    hostname: tycspider
    volumes:
      - type: bind
        source: /usr/local/tycspider/svrinclude/
        target: /etc/supervisor.conf.d/include/
      - type: bind
        source: /usr/local/tycspider/tianyanchaSpider/
        target: /usr/src/app/
      - type: bind
        source: /var/log/tycspider/
        target: /var/log/project/
      - type: bind
        source: /dev/shm/
        target: /dev/shm/
networks:
  cct-backstage:
    external: true
  
